apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuval-onboarding-app-deployment
  namespace: yuval-onboarding-app
  labels:
    app: yuval-onboarding-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yuval-onboarding-app
  template:
    metadata:
      labels:
        app: yuval-onboarding-app
    spec:
      containers:
        - name: yuval-onboarding-app-container
          image: us-central1-docker.pkg.dev/atals-feed-dev/yuval-onboarding/my-app:v1.2-amd64
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: yuval-onboarding-app-service
spec:
  selector:
    app: yuval-onboarding-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080